### ISSUE TITLE
Allow benchmarkpkg to commit results

### ISSUE THREAD

**Issue by quinnj** [JuliaCI/PkgBenchmark.jl#8] opened 2016-10-13 07:03 UTC
Ultimately, I'd love for travis to benchmark my package with every commit, for this, I believe benchmarkpkg would need to be able to commit the results of the `.jld` file it generates.

**Comment by shashi** [comment] 2016-10-13 07:06
the problem is contributors who want to benchmark may be on a different machine. We can very well allow this and let people use it if they are sure they want to.

**Comment by quinnj** [comment] 2016-10-13 07:18
I think my request would actually make this better then, right? Since all benchmarking would happen on travis instead of people's local machines? I mean, there's obviously the potential problem of travis capacity/usage, but it seems like that may be better to deal with than the various machines that people might be using.

**Comment by tkelman** [comment] 2016-10-14 05:49
Travis is almost certainly less uniform than running on a local machine. Only comparisons between runs on the same machine will be all that meaningful, and the benchmark results should store some data about the system where they ran.

**Comment by KristofferC** [comment] 2017-07-16 12:29
I feel storing benchmarks result in the repo itself is not optimal. It might fairly quickly increase the size of the repo and you might want to have data for different releases, branches etc. I feel some sort of external database would suit better?

**Comment by Evizero** [comment] 2017-07-16 12:33
HDF5 is also not very git friendly as far as I am aware

**Comment by KristofferC** [comment] 2017-07-20 18:52
I'll close this since storing jld files (that happens to often be quite large) on every commit will blow up repo size and probably not a good idea for this package.

**Closed by KristofferC** 2017-07-20 18:52 UTC
